spring.application.name=Library
server.port=8080

# 1. Подключение через переменные окружения
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Явная настройка пула подключений HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# Настройки Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Настройки сессий и безопасности
server.servlet.session.cookie.name=MYAPP_SESSION
spring.security.logout.delete-cookies=MYAPP_SESSION
spring.security.logout.logout-success-url=/login?logout

# Обеспечивает стабильный формат JSON для пагинации в REST API
spring.data.web.pageable.page-serialization-mode=via-dto